spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studentMgment
    username: root
    password: 12345678

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: update
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG